---
# Install Logstash packages on redhat base distributions.

- name: Add the Logstash RPM key.
  rpm_key: state=present key=https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add the Logstash repository.
  yum_repository:
    name: Logstash-repository
    description: Logstash repository for 5.x packages.
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgcheck: yes
    enabled: yes
    file: logstash

- name: Install Logstash package.
  yum: name=logstash update_cache=yes state=latest

- name: Configure Logstash.
  include: logstash.yml
